[package]
name = "sfdrsine"
version = "0.1.0"
edition = "2021"
authors = ["Bart Massey <bart@cs.pdx.edu>"]

[dependencies]
ordered-float = "3.0.0"
rayon = "1.5.3"

[[bin]]
name = "sfdrsine"
path = "sfdrsine.rs"
